### ISSUE TITLE
Add dynamic suggestion arguments

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/1.13-Command-API#24]
Suggestions (by means of the SuggestedStringArgument) can only be defined at command registration. Implement a method to create dynamic arguments which are determined at runtime, perhaps by means of a functional interface.

_Technical notes:_
_Functional interface should be parsed into a suggestion provider builder, which uses [this code here](https://github.com/JorelAli/1.13-Command-API/blob/master/1.13CommandAPI/src/io/github/jorelali/commandapi/api/SemiReflector.java#L591)_

**Comment by JorelAli** [comment]
Implemented dynamic arguments in [this commit](https://github.com/JorelAli/1.13-Command-API/commit/9c4f63bb6082c8f10134a2ccf86b575f83f35a98)

Sample code used for testing:
```java
//This is initialized somewhere
static List<String> arr = new ArrayList<>();

LinkedHashMap<String, Argument> arguments = new LinkedHashMap<>();
arguments.put("element", new StringArgument());
CommandAPI.getInstance().register("addToArr", arguments, (sender, args) -> {
	arr.add((String) args[0]);
	System.out.println("Added " + args[0] + " to list");
});

arguments.clear();
arguments.put("suggested", new DynamicSuggestedStringArgument(() -> {return arr.toArray(new String[arr.size()]);}));
CommandAPI.getInstance().register("dynsuggest", arguments, (sender, args) -> {
	System.out.println((String) args[0]);
});
```

Example usage:
```
/addtoarr hello
/addtoarr world
/addtoarr blah
```
When typing `/dynsuggest`, the following suggestions are shown:

![img](https://i.imgur.com/7F7e0mf.png)

**Comment by Combustible** [comment]
I noticed one more thing that's interesting about the way this API is set up.

Minecraft isn't actually taking into account the characters you start typing for the suggestions. So for example if you have "alice" and "bob" as suggestions, if you start typing "bo", it calls the completer and asks for the completions - which returns "alice" and "bob". So minecraft returns possible completions "alice" and "bob" to the client. The problem is - "alice" is not a valid completion for "bo". 

I'm not sure if you can get at the client's partially completed string - but I bet you can. If so, can you pass that in as an argument to the functional interface? Then when I implement my dynamic completion callback I can look at the partial match and only supply back suggestions that match it. 

Thanks!
