### ISSUE TITLE
Update to support 1.14?

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#45]
Hello, I've discovered your plugin and it's pretty well written but 1.14 recently came out and your plugin's dependence on NMS and Reflection has caused it to stop to work. 
Have you considered getting your command api to run in 1.14 (I think the system is very similar and only requires changing to new NMS mappings to get it to run again)? 
Thanks.

**Comment by JorelAli** [comment]
I do plan to update this to 1.14 and have been working on it as we speak!

**Comment by i509VCB** [comment]
Thanks man, why don't you post this as a resource on Spigot?, I know people have linked to your project from there but more people can get to it if you upload it there.

**Comment by JorelAli** [comment]
https://www.spigotmc.org/resources/1-13-commandapi.62353/

Yeah, I could touch up on the page a bit more...

**Comment by JorelAli** [comment]
Status update:
Progress for the 1.14 update is coming along smoothly. The current repository is in a bit of a state and I plan to rectify that before its release (involves finishing off half-baked features).

I have this exam in a few days _(so will probably be a little inactive)_ however after that I plan to work on this project full time and push it out ASAP!

**Comment by JorelAli** [comment]
# Status update
1.14's compatibility changes have been implemented (i.e. fixing the inconsistencies with NMS mappings). 

## Documentation
Due to the large difference between the latest release _(1.8.2)_ and the current master branch, a lot of documentation needs to be written to explain a bunch of fancy new features. In the process of writing the documentation, I noticed a lot of invalid code _(old examples which don't work)_ and have decided to rewrite the entire documentation from scratch. Sure, it's a large portion of the project that I didn't really want to work on, but I truly believe that this documentation change will be for the better!

When I released 1.8, it was pretty dire - it had a massive flaw which was only discovered upon updating the documentation _(yes, I pushed out a release before the documentation once... it was not a good time)._ In order to never make that mistake again, documentation takes priority at the moment

## Testing
The CommandAPI is anything but a small project. As such, testing the CommandAPI is incredibly tedious _(Almost all tests are performed manually because they have to be executed ingame as a player and results have to be 'seen'. In other words, I have to actually see whether they produce the results because certain tests take place before executing commands)._ Due to this, I cannot confirm with 100% certainty that the CommandAPI will be fully bug free - issue #43 has been a long standing issue _(almost 4 months now)_ and still hasn't "really" got any working solution yet.

## ETA?
Hopefully, the 1.14 release should come out by the end of this week _(So ideally, **expect a release by 13th May**, but I'm not making any promises!)_

**Comment by i509VCB** [comment]
Well I have some news, 1.14.1 is coming out on the 13th which is bad news for all the bleeding edge people using your plugin. Good news is it should be as simple as change like 3 mappings for you to get it working on 1.14.1 due to minimal changes.

**Comment by JorelAli** [comment]
> Well I have some news, 1.14.1 is coming out on the 13th which is bad news for all the bleeding edge people using your plugin. Good news is it should be as simple as change like 3 mappings for you to get it working on 1.14.1 due to minimal changes.

Thanks for the heads up. I will mention that _md\_5_ has stated that current support for 1.14 is a development build and _"is not ready for use on a production server"_.

I'm sort of on the fence when it comes to bleeding edge developers using my plugin - knowing that there's bleeding edge devs out there puts pressure to push releases out quickly. Then again, spigot have been known for taking time to push out stable versions of their software _(for obvious reasons)_, so I'm not in a major hurry. 

For now, I've pushed out a pre-release build which contains the current latest copy of the CommandAPI for 1.14 support [here](https://github.com/JorelAli/1.13-Command-API/tree/No-Reflection/1.13CommandAPI/pre-release%20builds). Feel free to try it out _(if you choose to do so, and you notice any bugs, I'd be grateful if you'd open a bug report)_.

I don't plan to put any development versions of the CommandAPI on the maven repo.

**Comment by i509VCB** [comment]
I tested and your plugin seems to work in 1.14.1 (Yes spigot and paper already updated). (Haven't done much more testing than a basic plugin). 
So far I haven't found any bugs (definitely cant test Dynamic Strings until you release documentation) but take your time with the documentation.

**Comment by JorelAli** [comment]
Documentation for 1.14 is slowwwwwwwwly coming along - it's come to my attention that it's taking a little longer than expected _(I had a massive phase of trying to add unit tests and that took way longer than I expected)_

To make up for it, I've pushed out another pre-release build: [CommandAPI_2.0_20190517-135405.jar](https://github.com/JorelAli/1.13-Command-API/tree/No-Reflection/1.13CommandAPI/pre-release%20builds). This build _should_ be the final version before the actual release - if there's any bugs with this, then that'll be pretty problematic. This version has a bunch of changes to make version handling much more stable.

**Comment by JorelAli** [comment]
# Status update
We're in the home stretch now! The documentation has only got 1 more large section to cover _(resulting command executors)_, and then a few small bits here and there _(aliases; how to use arguments; dynamic suggestions)_. Trust me, we're so almost there!

Of course, after writing the documentation, a phase of testing will have to take place. Considering that the CommandAPI is basically untestable without creating test plugins and paying attention to how they perform _(trust me, I've tried writing unit tests - the CommandAPI detests unit tests and does not cooperate in the slighest)_, this could take an eternity. Instead, I plan to release the API as the latest pre-release build _(I've made no changes to the code since then, and everything looks like it's running smoothly)_

And of course, when 2.0 comes out, it'll be available on the maven repository for everyone to use!

**ETA: Less than 24 hours.**

**Comment by JorelAli** [comment]
The CommandAPI version 2.0 has been released, with support for Minecraft 1.14 and 1.14.1
Read the new documentation here: https://jorelali.github.io/1.13-Command-API/
