### ISSUE TITLE
Registered commands do not survive reload

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#46]
Issue happens in 1.8.2 & 2.0 (MC 1.13.2 & 1.14), maybe even earlier. 

With any command I register using this plugin, when I use /reload all registered commands by the plugin do not work any more and server requires a restart to go back to normal. 

Unregistering commands on enable before they loaded again does not fix the issue either. 

Also no error logs show up in console.

**Comment by JorelAli** [comment]
Yup. This is intended. I literally wrote the documentation about this last night.

Basically, `/reload` is **bad**, for many many many many reasons. 

* The number 1 reason why `/reload` is bad is that it causes memory leaks. Due to the implementation of `/reload`, it's impossible to properly free up the memory that certain plugins use. Unfortunately, one of the plugin that use some of this "unfreeable memory" is the CommandAPI - in particular, it's main instance which is used to register commands. Classes with static variables _(constants, HashMaps containing cached information)_ aren't unloaded when using `/reload`.
* "The /reload command was built and designed for development purposes. It is not for production servers."
* The `/reload` command was never designed to be used with plugins. Think about it, the `/reload` command would have to take into account EVERY POSSIBLE plugin and handle a graceful unload sequence and loading sequence. This becomes basically impossible for any "complex" level plugin. For example, take any plugin that uses any sort of multithreading _(for example, using an async task to communicate with a database)_. Because there are multiple threads that are being "used" by the plugin, the `/reload` command reloads the plugin but _**does not stop those threads**_. This means that you'll have arbitrary code running in the background ready to be sent back to a plugin that's not ready to receive such information.

In short, the `/reload` command is _**not recommended**_, _(even by the Spigot team themselves - they output a warning saying that plugins aren't supported when you run it)_.

> Please note that this command is not supported and may cause issues when using some plugins.
> If you encounter any issues please use the /stop command to restart your server.

------

In addition to the fact that the `/reload` command is _bad_, don't forget that the CommandAPI doesn't do things "the normal way". The CommandAPI directly hooks into the vanilla command registration system and links it to a Bukkit plugin system. If the Bukkit plugin system is completely unloaded and restarted, the registered Vanilla commands suddenly are not linked to anything. Fixing this unlinking and re-linking _may_ be possible by using the CommandAPI's unregistration function*, however for the reasons stated above, I don't plan to add any support for surviving reloads.

\*_For example, if the unregistering phase occurred in the onDisable method?_

-----

In conclusion, I designed the CommandAPI to not survive reloads. It's incredibly difficult to write a plugin which will work normally when at any unexpected time, the entire thing shuts down and old variables stay in memory.

**Comment by JorelAli** [comment]
Limited support for `/reload` was added in version 6.3.1. Unregistering commands in the `onDisable()` method will allow `/reload` to re-register your command on reload.
More information about this can be found in the [Plugin reloading section of the documentation](https://commandapi.jorel.dev/6.4.0/reloading.html)
