### ISSUE TITLE
Add another overloading of CommandAPI.fail to take an argument of a supplier for failure message

### ISSUE THREAD

**Issue by i509VCB** [JorelAli/1.13-Command-API#56]
**Please describe your suggestion**
The idea is to allow a developer to supply a message with a supplier to provide the failure message of a command. This could be useful for language systems where the plugin may send the command result to each player in a different language.

**Possible code option**
```java
public static void fail(Supplier<String> messageSupplier) throws WrapperCommandSyntaxException {
    throw new WrapperCommandSyntaxException(new SimpleCommandExceptionType(new LiteralMessage(messageSupplier.get())).create());
}
```

**Comment by JorelAli** [comment]
Hold on. What's to stop you from say, using this:

```java
CommandAPI.getInstance().register("locale", null, (s, a) -> {
    Player p = (Player) s;
    CommandAPI.fail(I18N.getErrorMessage(p.getLocale()));
});
```
where I18N is some generic I18N class:

```java
class I18N {
    public static String getErrorMessage(String locale) {
        switch(locale) {
            case "en_us":
                return "An error message";
            case "fr_fr":
                return "Un message d'erreur";
            //Insert other cases here
            default:
                return "This locale is not supported";
        }
    }
}
```

-----

If my understanding is correct, the idea of using a supplier is such that when the error executes, it can generate a String at runtime _(i.e. at the time when the command is run)_. This is currently the case when using a regular String.

This basically makes it no different to using a `String` verses using a `Supplier<String>`

This code is basically the same as using the following - there's no benefit over using a `Supplier<String>` over a regular `String`
```java
CommandAPI.fail(() -> I18N.getErrorMessage(p.getLocale()));
```

**Comment by JorelAli** [comment]
Due to the reasons stated above, there's no benefit to overloading `CommandAPI.fail` with a `Supplier<String>` argument, because the `CommandAPI.fail` method should be used whilst a command is running (i.e. inside the command executor lambda), which is evaluated at execution time (which is the same time when the supplier would be evaluated).

Since they're both being evaluated at the same time, this makes the Supplier redundant.

Therefore, I will not be implementing a `Supplier<String>` method for the upcoming 2.1 release or any future releases.
