### ISSUE TITLE
New design that I made

### ISSUE THREAD

**Issue by portlek** [JorelAli/1.13-Command-API#63]
I've a project that's similar to your. I didn't finished the back-end registeration. 
My project: https://github.com/portlek/commands

Maybe this design gives you an idea. The front-end registration;
```java
public final class PlayerMarket extends JavaPlugin {

    private final Commands commands = new Commands(this);

    @Override
    public void onEnable() {
        // Plugin startup logic
        commands.init();

        commands.register(
            new CommandOf(
                "main-command-id",
                "sendMessage",
                argument(
                    new ArgumentOf(
                        "player-name",
                        new PlayerArgument(),
                        requirement(commandSource -> commandSource.getArgPlayer().isPresent()),
                        argument(
                            new ArgumentOf(
                                "message-text",
                                new GreedyStringArgument(),
                                execute(commandSource -> {
                                    commandSource.getArgPlayer("player").ifPresent(player -> {

                                        // /sendMessage <player> <message> executed!

                                        player.sendMessage(ChatColor.translateAlternateColorCodes('&', commandSource.getArgText()));
                                    });

                                    return true;
                                })
                            )
                        )
                    )
                )
            )
        );
    }

}
```

**Comment by JorelAli** [comment]
Hi,

I saw your plugin earlier (yesterday) and personally, don't plan to change the structure of the CommandAPI in the future. Due to the few people that are currently using my API, asking them to switch to entirely new syntax would seem unreasonable.

In addition, I personally prefer my syntax as it is a lot easier to format and comprehend at a glance as opposed to having multiple nested statements and arguments. I also personally do not like the idea of using static imports as it makes code more difficult to understand without knowledge of how the static import is used.

If you plan to create your own API, that's entirely fine by me, but I do not plan to change the CommandAPI in the foreseeable future.
