### ISSUE TITLE
Support of BungeeCord

### ISSUE THREAD

**Issue by orblazer** [JorelAli/1.13-Command-API#67]
**Please describe your suggestion**
Implement an support for bungeecord side.

In bungeecord cord side the arguments `location`, `entity` and `technical` arguments could just throw an Exception.

*Note:* i go investigate in next weeks for make that implementation

**Comment by JorelAli** [comment]
I do not know much or anything about how BungeeCord handles commands, let alone how BungeeCord handles ... anything really.

I literally know nothing about how to make something BungeeCord compatible, so I'll need all the help I can get if I want to support BungeeCord. Some code samples for accessing location, entities etc. would be useful, as well as some code samples on how cross-server commands work _(Again, I don't know much about cross-server commands, and especially have no idea if Vanilla Minecraft commands are compatible with BungeeCord servers since they're declared in a completely different way to Bukkit commands)_.

If it is possible to add BungeeCord support, I'm more than willing to help make it a reality, but on my own, I can't do much.

**Comment by i509VCB** [comment]
Adding direct bungee cord support could be possible but would require a further abstraction from the current api. Bungee cord does inject itself into the Command Tree packets so it can add commands. And bungee does intercept the command before reaching server.

However Bungee has no implementation of CommandListenerWrapper. So you'd have to make a second implementation of system including its own handling for tab completion (which bungee doesn't really support).

So an implementation of a command system that looks like this is definitely possible in a seperatw bungee exclusive spinoff but as a part of this plugin it wouldn't make sense due to the incompatable systems.

**Comment by JorelAli** [comment]
Since there's been no progress with this for over 2 months and such an idea would require _(according to i509VCB)_ a practical rewrite of the command system, I'm just gonna close this issue until further developments/contribution is made to push the CommandAPI in the direction of BungeeCord support.
