### ISSUE TITLE
Add `minecraft:operation` to go along with the rest of the scoreboard arguments.

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#79]
**Please describe your suggestion**
To finish off all scoreboard related arguments, we should add the operation one.

I mentioned it on the mega thread, but it got lost in it.

**Please supply examples of the desired inputs and outputs**
_Example:_
Input: `/personboard highscore += 10`
Output: the highscore slot in a scoreboard dedicated to the player is set to previous value plus 10.

**Comment by JorelAli** [comment]
Can do.

**Comment by JorelAli** [comment]
So, something just came to mind: The `minecraft:operation` argument is not as good as you expect it to be.

So, as to my implementation of it, it returns a `IntBinaryOperator`, which is basically a functional interface containing the method:
```java
int apply(int i, int j);
```

This would mean that if someone were to say use `/personboard highscore += 10`, the plugin developer would _not_ be able to determine _which_ operator they chose, all they can do is apply it to two arbitrary numbers.

-----

Also, Minecraft's operation argument is designed specifically for scoreboards. Hence, to make it more "Bukkit friendly", you would ideally only want to perform this operation on integers and then apply it to scoreboards manually. Therefore, there's [all of this trickery](https://github.com/JorelAli/1.13-Command-API/blob/5c9f090032cfc3ba4ef4220a291824e5832a088f/1.13CommandAPI/src/io/github/jorelali/commandapi/api/nms/NMS_1_13_R1.java#L649) to get around it in its implementation.

Also, the thing about scoreboards/objectives/teams etc. is that they weren't _really_ designed to be used by plugins. Command blocks are much more efficient _(computationally)_ compared to plugins and the commands that are used for them are designed specifically for those purposes _(`/execute`)_.

-----

My point is, having this argument is pretty redundant as:

- It has weird effects in trying to only let it be integers only. For example, the `><` operator which is designed to "switch" the values of two scoreboard scores doesn't do anything when applied to integers _(You can't do `5 >< 10`, it doesn't make sense)_
- Assignment makes no sense. Saying `2 = 20` doesn't make sense. At all.
- If you really want to make changes to scoreboard entries, commands _already exist_ that do so _(I personally don't know what these commands are, but that's not my "area of expertise" - all I know are people that know that these exist, because I've been on servers that do these operations solely using command blocks)_
- Most command designed incorporate it automatically to prevent confusion and for simplicity and elegance. For example, the built in Minecraft `/time` command has `/time set <time>` and `/time add <time>`, as opposed to `/time <mathop> <time>`. Sure you could use `/time = 0` or `/time += 12000`, but why would you?

**Comment by Minenash** [comment]
If we wanted this argument to return to the dev, what operator they used, then that's possible by having two dummy scores, and seeing what the result is. Like lets say the dummy values are 1 and 2. If it's a +=, then the the first dummy should be 3. Etc.

So now to the importance of it. I agree that I personally don't see the point of any scoreboard arguments, except of course, changing the format of the messages, or adding permission-based restrictions. And I think I've seen more than one "issue" opened about supporting it, so it's definitly wanted to some extent. The only reason I personally added all the scoreboard stuff to the mega-thread, was because you already had a CustomArgument-thing for it. Personally, if it's going to be supported, I rather it be supported all the way. For how the code can work:
```java
enum Operator {ADD, SUBTRACT, MULTIPLY, DIVIDE, MOD, ASSIGN, MIN, MAX, SWAP}
	
public Operator getMathOperation(CommandContext cmdCtx, String key) throws CommandSyntaxException {
	ArgumentMathOperation.a result = ArgumentMathOperation.a(cmdCtx, key);
	net.minecraft.server.v1_14_R1.Scoreboard board = new net.minecraft.server.v1_14_R1.Scoreboard();
	ScoreboardScore tester_left = new ScoreboardScore(board, null, null);
	ScoreboardScore tester_right = new ScoreboardScore(board, null, null);
	
	tester_left.setScore(6);
	tester_right.setScore(2);
	result.apply(tester_left, tester_right);
	
	switch (tester_left.getScore()) {
		case 8: return Operator.ADD;
		case 4: return Operator.SUBTRACT;
		case 12: return Operator.MULTIPLY;
		case 3: return Operator.DIVIDE;
		case 0: return Operator.MOD;
		case 6: return Operator.MAX;
		
		case 2: {
			if (tester_right.getScore() == 6)
				return Operator.SWAP;
			tester_left.setScore(2);
			tester_right.setScore(6);
			result.apply(tester_left, tester_right);
			if (tester_left.getScore() == 2)
				return Operator.MIN;
			return Operator.ASSIGN;
		}
	}
	return null;
}
```

**Comment by JorelAli** [comment]
I mean yeah, using a tester would work but holy that sure doesn't look elegant.

**Comment by Minenash** [comment]
Imo It's better than having a annomonos class

**Comment by Minenash** [comment]
Do you plan on adding this still? I know the switch case isn't the greatest thing, but it's more efficient and way more useful than the alternative. The best alternative to this type of argument are literals, and those make the tree quite a bit longer.

**Comment by JorelAli** [comment]
Despite the fact it's not an elegant solution in the slightest, it's still a solution that should work nonetheless. I do plan to include this in the 3.0 release. I'll close this issue once it's been implemented.
