### ISSUE TITLE
Use ParseResults to improve performance

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/1.13-Command-API#80]
**Please describe your suggestion**
Use parse results to improve performance.

**Relevant links:**
[Parsing user input (Brigadier docs)](https://github.com/Mojang/brigadier#parsing-user-input)

**Pseudocode**
_Creating a wrapped version of the parse results_
Basically, create parse results for a "default command sender"
```java
let cmdDispatcher = CommandAPIHandler.brigadierDispatcher

String command = command[0] == "/" ? command.substring(1) : command
ParseResults = cmdDispatcher .parse(command, NMSServer.getServerCommandListener())

WrappedParseResults = wrap(ParseResults)
```

_Executing the parse results_
```java
cmdDispatcher.execute(unwrap(WrappedParseResults))
```
Or:
Upon execution, change the command sender?
```java
let pr = unwrap(WrappedParseResults)
let playerContext:CommandListenerWrapper = NMSPlayer.getCommandListener();

cmdDispatcher.execute(new ParseResults<CommandListenerWrapper>(pr.getContext().withSource(playerContext), pr.getStartIndex(), pr.getReader(), pr.getExceptions()))
```

**Cache design**
```java
map<<CommandStr, BukkitCommandSender_UUID>, ParseResult>
```

**Comment by i509VCB** [comment]
Does MC not normally allow inputting parse results into their execute method in NMS CommandDispatcher?

The main issue is trying to prevent memory leaks.

Also I don't see any performance benefit unless you parse it (weather sync or async is a different question) while the user is typing the command. I checked protocol and the clients does not send tab Complete request unless it's an ask server request.

So one solution for real time live parsing could be to make the command register an ask server request at every single position within the command tree so the client sends current command line every single time the client makes a modification and also merge other preexisting suggestions into that fray without breaking anything else. This is odd and only partially plausible. 

Now if this were the client this would be easy since the client does use parse results in real time.

**Comment by JorelAli** [comment]
It's currently just a suggestion, but for clarification, you can use parse results to reduce the overhead of parsing user input. You could look it up in some form of cache and it goes straight to execution instead. NMS does let you execute parse results once they've been generated.

The idea would be if say you have a command block on some form of loop (say you run some command 20 times a second, it could get very intense).

The major issue as you've said would be memory leaks and I honestly haven't thought of a workaround for it. For now, this idea is just speculation.

I don't plan to include this in the 3.0 release, but it's a potential idea for the far future and I thought it would be good to note down.
