### ISSUE TITLE
Add ability to have any argument type be used for dynamic suggestions

### ISSUE THREAD

**Issue by Michael-Ziluck** [JorelAli/1.13-Command-API#85]
**Please describe your suggestion**
Currently, the only way to have dynamic argument types is to use `DynamicSuggestedStringArgument` which is quite limiting. There are two enhancements to it that would make it amazing to use:

1. Allow it to accept any of the existing types as its own
2. Have it validate that the selected option is valid

Examples of when this would be practical is say, for instance, a plugin tracks a list of Materials that can be sold in an economy plugin. If someone wanted to do a command like `/addmaterial [material]`, they would only be able to enter materials that are not currently tracked, and vice versa.

**Comment by JorelAli** [comment]
> 1. Allowing it to accept any of the existing types as its own

Sounds like a great idea, it shouldn't be too difficult to extend the arguments that can have custom suggestions to include the dynamic suggestions.

> 2. Have it validate that the selected option is valid

I'll have to look into this. I don't think it'll be easy, but it shouldn't be impossible.

**Comment by JorelAli** [comment]
Commits from b1290a7b871fa5cf30caecdb5400a06bb538a626 to 8a920e2fa98c4c66d01d70a0da3c959d693467ab include support for dynamic suggestions for all argument types. This implementation does not validate if the selected option is valid, since that's pretty difficult to do :confused:

**Comment by JorelAli** [comment]
> 2. Have it validate that the selected option is valid

I've begun testing various solutions to validate that the selected option is valid. This has lead to this minor dilemma:

- If the developer chooses to use static suggestions (e.g. `.overrideSuggestions(String[])`), then the CommandAPI should be able to check that the elements of the `String[]` are valid when the command is being registered.
- If the developer chooses to use dynamic suggestions (e.g. `.overrideSuggestions((sender) -> String[])`), then the CommandAPI will not be able to check the elements of the resulting `String[]` are valid until runtime, i.e. when a sender runs the command.

Ideally, checking both statically would be ideal...

-----

Alternatively, we change the `.overrideSuggestions()` method to be specific to the return class of an argument. For example, we could change it so that for the `ChatColorArgument`, the `overrideSuggestions` methods would be of the following type:
```java
T overrideSuggestions(ChatColor[]);
T overrideSuggestions(Function<CommandSender, ChatColor[]>);
```

This method however would be time consuming (but not impossible!) to implement

**Comment by JorelAli** [comment]
Since the main issue of adding dynamic suggestions to any argument type has been completed, I'm closing this issue. I've opened up a new issue to outline your original second suggestion.
