### ISSUE TITLE
Add `.executesConsole()`

### ISSUE THREAD

**Issue by Minenash** [JorelAli/1.13-Command-API#88]
**Please describe your suggestion**
An executor, that works just like it's brothers, but for ConsoleSenders instead of Players, Entities, or Command Blocks.

**Please supply examples of the desired inputs and outputs**
_Example:_
```java
new CommandAPICommand("csay")
    .withArguments(/*arguments*/)
    .withAliases("consolesay")
    .executes((sender, args) -> {
        Bukkit.getServer().broadcastMessage("[Console]: " + ( (String) args[0] ));
    });
```

**Comment by JorelAli** [comment]
Yeah, I'm aware that I should have added this - I have no idea why I haven't yet. I will make sure it gets added for the 3.0 release.

**Comment by Minenash** [comment]
Nice to see you working on this again! Not sure adding a feature is a fix, but to each their own. 🙂

**Comment by JorelAli** [comment]
Yeah, totally messed up that commit message. Oh well. According to the timetable, I'm supposed to be working on implementing the features from the list of issues:

| December 2019 - January 2020 | Work on implementing new features from issues |
| -- | -- |

This may or may not go as planned, due to a huge amount of university workload that I have due January. (Just thought I'd let you know)

**Comment by Minenash** [comment]
> Just thought I'd let you know
Always nice to know 🙂

> According to the timetable, I'm supposed to be working on implementing the features from the list of issues:
If it were I who wrote that, I'd've either started in October or in March. So I'm glad you're better than I when it comes to actually following a time table!
